title: Empty Words
description: ""
baseurl: ""
url: ""
permalink: /:categories/:title/
github_username:  costajob
linkedin_username: michelecosta
instagram_username: agilestyle73

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
